Your RMarkdown should include the following topics. Depending on your project type, the amount of discussion you devote to each of them will vary:

# Overview and Motivation
* Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal.

# Related Work
* Anything that inspired you, such as a paper, a web site, or something we discussed in class.

# Initial Questions
* What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?

# Data
* Source, scraping method, cleanup, etc.

# Exploratory Analysis
* What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions?

# Final Analysis
* What did you learn about the data? How did you answer the questions? How can you justify your answers?


* * *
# Project Proposal
###### Background and Motivation
Discuss your motivations and reasons for choosing this project, especially any background or research interests that may have influenced your decision.

Our political climate seems more polarized than ever. Protests are occurring more frequently and people are documenting their actions, sentiments, and events via social media. Parsing data from Twitter (bytes of bigger conversations) can capture fleeting emotions and solidify networks within a subgroup.  We will examine the recent “White Lives Matter” rally that took place on the weekend of October 28-29, in two cities in Tennessee: Murfreesboro and Shelbyville.  Although it generated less notoriety than the similar “Unite the Right” rally in the Charlottesville, VA, this rally generated a significant amount of activity on Twitter (over 66,000 tweets).  Moreover the rally generated two distinct groups: the members of the “White Lives Matter” group and the counter protesters who organized against the original rally.


###### Project Objectives
What are the scientific and inferential goals for this project? What would you like to learn and accomplish? List the benefits. What are some optional features (features or calculations which you consider would be nice to have, but not critical)?

The goals of this project is to use sentiment analysis (using an R package for natural language processing, RSentiment) to gauge the feelings surrounding a protest during the periods preceding, during and immediately after an event takes place.  Moreover we wish to assess how the  portrayal of a protest or controversial event on social media reflects the actual occurrences “on the ground.”

Goals: 
Identify networks of individuals who are active on Twitter during the event
Attempt to associate shifts in sentiment on social media with subevents that occur during the larger event of interest
Make a statement about ideal law enforcement deployment times/locations based off of social network activity spikes
 
###### What Data?
From where and how are you collecting your data?

We are using the twitteR package to interface with Twitter and read tweets that are localized to a certain location and timeframe. An initial pull attempt has compiled Twitter data from the general locale of Murfreesboro, Tennessee where a protest and counter-protest occurred on 10/28/2017. 

###### Design Overview
List the statistical and computational methods you plan to use.

Sentiment analysis of tweets over the duration of the event. Network analysis using either tie strength, homophily, mutuality, or network closure as the primary measure. Social networking potential (SNP) algorithms will also be used to identify individuals with large social networking potential. Frequentist and Bayesian methods will be used to identify changes in sentiment throughout the course of the event.

###### Schedule / timeline
Make sure that you plan your work so that you can avoid a big rush right before the final project deadline, and delegate different modules and responsibilities among your team members. Write this in terms of weekly deadlines.
